.class public Lnl/siegmann/epublib/domain/Metadata;
.super Ljava/lang/Object;
.source "Metadata.java"

# interfaces
.implements Ljava/io/Serializable;


# static fields
.field public static final DEFAULT_LANGUAGE:Ljava/lang/String; = "en"

.field private static final serialVersionUID:J = -0x21d2e5af30d4cc44L


# instance fields
.field private authors:Ljava/util/List;
    .annotation system Ldalvik/annotation/Signature;
        value = {
            "Ljava/util/List<",
            "Lnl/siegmann/epublib/domain/Author;",
            ">;"
        }
    .end annotation
.end field

.field private autoGeneratedId:Z

.field private contributors:Ljava/util/List;
    .annotation system Ldalvik/annotation/Signature;
        value = {
            "Ljava/util/List<",
            "Lnl/siegmann/epublib/domain/Author;",
            ">;"
        }
    .end annotation
.end field

.field private dates:Ljava/util/List;
    .annotation system Ldalvik/annotation/Signature;
        value = {
            "Ljava/util/List<",
            "Lnl/siegmann/epublib/domain/Date;",
            ">;"
        }
    .end annotation
.end field

.field private descriptions:Ljava/util/List;
    .annotation system Ldalvik/annotation/Signature;
        value = {
            "Ljava/util/List<",
            "Ljava/lang/String;",
            ">;"
        }
    .end annotation
.end field

.field private format:Ljava/lang/String;

.field private identifiers:Ljava/util/List;
    .annotation system Ldalvik/annotation/Signature;
        value = {
            "Ljava/util/List<",
            "Lnl/siegmann/epublib/domain/Identifier;",
            ">;"
        }
    .end annotation
.end field

.field private language:Ljava/lang/String;

.field private metaAttributes:Ljava/util/Map;
    .annotation system Ldalvik/annotation/Signature;
        value = {
            "Ljava/util/Map<",
            "Ljava/lang/String;",
            "Ljava/lang/String;",
            ">;"
        }
    .end annotation
.end field

.field private otherProperties:Ljava/util/Map;
    .annotation system Ldalvik/annotation/Signature;
        value = {
            "Ljava/util/Map<",
            "Ljavax/xml/namespace/QName;",
            "Ljava/lang/String;",
            ">;"
        }
    .end annotation
.end field

.field private publishers:Ljava/util/List;
    .annotation system Ldalvik/annotation/Signature;
        value = {
            "Ljava/util/List<",
            "Ljava/lang/String;",
            ">;"
        }
    .end annotation
.end field

.field private rights:Ljava/util/List;
    .annotation system Ldalvik/annotation/Signature;
        value = {
            "Ljava/util/List<",
            "Ljava/lang/String;",
            ">;"
        }
    .end annotation
.end field

.field private subjects:Ljava/util/List;
    .annotation system Ldalvik/annotation/Signature;
        value = {
            "Ljava/util/List<",
            "Ljava/lang/String;",
            ">;"
        }
    .end annotation
.end field

.field private titles:Ljava/util/List;
    .annotation system Ldalvik/annotation/Signature;
        value = {
            "Ljava/util/List<",
            "Ljava/lang/String;",
            ">;"
        }
    .end annotation
.end field

.field private types:Ljava/util/List;
    .annotation system Ldalvik/annotation/Signature;
        value = {
            "Ljava/util/List<",
            "Ljava/lang/String;",
            ">;"
        }
    .end annotation
.end field


# direct methods
.method public constructor <init>()V
    .locals 3

    .line 46
    invoke-direct {p0}, Ljava/lang/Object;-><init>()V

    const/4 v0, 0x1

    .line 30
    iput-boolean v0, p0, Lnl/siegmann/epublib/domain/Metadata;->autoGeneratedId:Z

    .line 31
    new-instance v1, Ljava/util/ArrayList;

    invoke-direct {v1}, Ljava/util/ArrayList;-><init>()V

    iput-object v1, p0, Lnl/siegmann/epublib/domain/Metadata;->authors:Ljava/util/List;

    .line 32
    new-instance v1, Ljava/util/ArrayList;

    invoke-direct {v1}, Ljava/util/ArrayList;-><init>()V

    iput-object v1, p0, Lnl/siegmann/epublib/domain/Metadata;->contributors:Ljava/util/List;

    .line 33
    new-instance v1, Ljava/util/ArrayList;

    invoke-direct {v1}, Ljava/util/ArrayList;-><init>()V

    iput-object v1, p0, Lnl/siegmann/epublib/domain/Metadata;->dates:Ljava/util/List;

    const-string v1, "en"

    .line 34
    iput-object v1, p0, Lnl/siegmann/epublib/domain/Metadata;->language:Ljava/lang/String;

    .line 35
    new-instance v1, Ljava/util/HashMap;

    invoke-direct {v1}, Ljava/util/HashMap;-><init>()V

    iput-object v1, p0, Lnl/siegmann/epublib/domain/Metadata;->otherProperties:Ljava/util/Map;

    .line 36
    new-instance v1, Ljava/util/ArrayList;

    invoke-direct {v1}, Ljava/util/ArrayList;-><init>()V

    iput-object v1, p0, Lnl/siegmann/epublib/domain/Metadata;->rights:Ljava/util/List;

    .line 37
    new-instance v1, Ljava/util/ArrayList;

    invoke-direct {v1}, Ljava/util/ArrayList;-><init>()V

    iput-object v1, p0, Lnl/siegmann/epublib/domain/Metadata;->titles:Ljava/util/List;

    .line 38
    new-instance v1, Ljava/util/ArrayList;

    invoke-direct {v1}, Ljava/util/ArrayList;-><init>()V

    iput-object v1, p0, Lnl/siegmann/epublib/domain/Metadata;->identifiers:Ljava/util/List;

    .line 39
    new-instance v1, Ljava/util/ArrayList;

    invoke-direct {v1}, Ljava/util/ArrayList;-><init>()V

    iput-object v1, p0, Lnl/siegmann/epublib/domain/Metadata;->subjects:Ljava/util/List;

    .line 40
    sget-object v1, Lnl/siegmann/epublib/service/MediatypeService;->EPUB:Lnl/siegmann/epublib/domain/MediaType;

    invoke-virtual {v1}, Lnl/siegmann/epublib/domain/MediaType;->getName()Ljava/lang/String;

    move-result-object v1

    iput-object v1, p0, Lnl/siegmann/epublib/domain/Metadata;->format:Ljava/lang/String;

    .line 41
    new-instance v1, Ljava/util/ArrayList;

    invoke-direct {v1}, Ljava/util/ArrayList;-><init>()V

    iput-object v1, p0, Lnl/siegmann/epublib/domain/Metadata;->types:Ljava/util/List;

    .line 42
    new-instance v1, Ljava/util/ArrayList;

    invoke-direct {v1}, Ljava/util/ArrayList;-><init>()V

    iput-object v1, p0, Lnl/siegmann/epublib/domain/Metadata;->descriptions:Ljava/util/List;

    .line 43
    new-instance v1, Ljava/util/ArrayList;

    invoke-direct {v1}, Ljava/util/ArrayList;-><init>()V

    iput-object v1, p0, Lnl/siegmann/epublib/domain/Metadata;->publishers:Ljava/util/List;

    .line 44
    new-instance v1, Ljava/util/HashMap;

    invoke-direct {v1}, Ljava/util/HashMap;-><init>()V

    iput-object v1, p0, Lnl/siegmann/epublib/domain/Metadata;->metaAttributes:Ljava/util/Map;

    .line 47
    iget-object v1, p0, Lnl/siegmann/epublib/domain/Metadata;->identifiers:Ljava/util/List;

    new-instance v2, Lnl/siegmann/epublib/domain/Identifier;

    invoke-direct {v2}, Lnl/siegmann/epublib/domain/Identifier;-><init>()V

    invoke-interface {v1, v2}, Ljava/util/List;->add(Ljava/lang/Object;)Z

    .line 48
    iput-boolean v0, p0, Lnl/siegmann/epublib/domain/Metadata;->autoGeneratedId:Z

    return-void
.end method


# virtual methods
.method public addAuthor(Lnl/siegmann/epublib/domain/Author;)Lnl/siegmann/epublib/domain/Author;
    .locals 1

    .line 80
    iget-object v0, p0, Lnl/siegmann/epublib/domain/Metadata;->authors:Ljava/util/List;

    invoke-interface {v0, p1}, Ljava/util/List;->add(Ljava/lang/Object;)Z

    return-object p1
.end method

.method public addContributor(Lnl/siegmann/epublib/domain/Author;)Lnl/siegmann/epublib/domain/Author;
    .locals 1

    .line 92
    iget-object v0, p0, Lnl/siegmann/epublib/domain/Metadata;->contributors:Ljava/util/List;

    invoke-interface {v0, p1}, Ljava/util/List;->add(Ljava/lang/Object;)Z

    return-object p1
.end method

.method public addDate(Lnl/siegmann/epublib/domain/Date;)Lnl/siegmann/epublib/domain/Date;
    .locals 1

    .line 68
    iget-object v0, p0, Lnl/siegmann/epublib/domain/Metadata;->dates:Ljava/util/List;

    invoke-interface {v0, p1}, Ljava/util/List;->add(Ljava/lang/Object;)Z

    return-object p1
.end method

.method public addDescription(Ljava/lang/String;)Ljava/lang/String;
    .locals 1

    .line 165
    iget-object v0, p0, Lnl/siegmann/epublib/domain/Metadata;->descriptions:Ljava/util/List;

    invoke-interface {v0, p1}, Ljava/util/List;->add(Ljava/lang/Object;)Z

    return-object p1
.end method

.method public addIdentifier(Lnl/siegmann/epublib/domain/Identifier;)Lnl/siegmann/epublib/domain/Identifier;
    .locals 2

    .line 176
    iget-boolean v0, p0, Lnl/siegmann/epublib/domain/Metadata;->autoGeneratedId:Z

    const/4 v1, 0x0

    if-eqz v0, :cond_0

    iget-object v0, p0, Lnl/siegmann/epublib/domain/Metadata;->identifiers:Ljava/util/List;

    invoke-interface {v0}, Ljava/util/List;->isEmpty()Z

    move-result v0

    if-nez v0, :cond_0

    .line 177
    iget-object v0, p0, Lnl/siegmann/epublib/domain/Metadata;->identifiers:Ljava/util/List;

    invoke-interface {v0, v1, p1}, Ljava/util/List;->set(ILjava/lang/Object;)Ljava/lang/Object;

    goto :goto_0

    .line 179
    :cond_0
    iget-object v0, p0, Lnl/siegmann/epublib/domain/Metadata;->identifiers:Ljava/util/List;

    invoke-interface {v0, p1}, Ljava/util/List;->add(Ljava/lang/Object;)Z

    .line 181
    :goto_0
    iput-boolean v1, p0, Lnl/siegmann/epublib/domain/Metadata;->autoGeneratedId:Z

    return-object p1
.end method

.method public addPublisher(Ljava/lang/String;)Ljava/lang/String;
    .locals 1

    .line 154
    iget-object v0, p0, Lnl/siegmann/epublib/domain/Metadata;->publishers:Ljava/util/List;

    invoke-interface {v0, p1}, Ljava/util/List;->add(Ljava/lang/Object;)Z

    return-object p1
.end method

.method public addTitle(Ljava/lang/String;)Ljava/lang/String;
    .locals 1

    .line 143
    iget-object v0, p0, Lnl/siegmann/epublib/domain/Metadata;->titles:Ljava/util/List;

    invoke-interface {v0, p1}, Ljava/util/List;->add(Ljava/lang/Object;)Z

    return-object p1
.end method

.method public addType(Ljava/lang/String;)Ljava/lang/String;
    .locals 1

    .line 200
    iget-object v0, p0, Lnl/siegmann/epublib/domain/Metadata;->types:Ljava/util/List;

    invoke-interface {v0, p1}, Ljava/util/List;->add(Ljava/lang/Object;)Z

    return-object p1
.end method

.method public getAuthors()Ljava/util/List;
    .locals 1
    .annotation system Ldalvik/annotation/Signature;
        value = {
            "()",
            "Ljava/util/List<",
            "Lnl/siegmann/epublib/domain/Author;",
            ">;"
        }
    .end annotation

    .line 85
    iget-object v0, p0, Lnl/siegmann/epublib/domain/Metadata;->authors:Ljava/util/List;

    return-object v0
.end method

.method public getContributors()Ljava/util/List;
    .locals 1
    .annotation system Ldalvik/annotation/Signature;
        value = {
            "()",
            "Ljava/util/List<",
            "Lnl/siegmann/epublib/domain/Author;",
            ">;"
        }
    .end annotation

    .line 97
    iget-object v0, p0, Lnl/siegmann/epublib/domain/Metadata;->contributors:Ljava/util/List;

    return-object v0
.end method

.method public getDates()Ljava/util/List;
    .locals 1
    .annotation system Ldalvik/annotation/Signature;
        value = {
            "()",
            "Ljava/util/List<",
            "Lnl/siegmann/epublib/domain/Date;",
            ">;"
        }
    .end annotation

    .line 73
    iget-object v0, p0, Lnl/siegmann/epublib/domain/Metadata;->dates:Ljava/util/List;

    return-object v0
.end method

.method public getDescriptions()Ljava/util/List;
    .locals 1
    .annotation system Ldalvik/annotation/Signature;
        value = {
            "()",
            "Ljava/util/List<",
            "Ljava/lang/String;",
            ">;"
        }
    .end annotation

    .line 172
    iget-object v0, p0, Lnl/siegmann/epublib/domain/Metadata;->descriptions:Ljava/util/List;

    return-object v0
.end method

.method public getFirstTitle()Ljava/lang/String;
    .locals 4

    .line 130
    iget-object v0, p0, Lnl/siegmann/epublib/domain/Metadata;->titles:Ljava/util/List;

    const-string v1, ""

    if-eqz v0, :cond_2

    invoke-interface {v0}, Ljava/util/List;->isEmpty()Z

    move-result v0

    if-eqz v0, :cond_0

    goto :goto_0

    .line 133
    :cond_0
    iget-object v0, p0, Lnl/siegmann/epublib/domain/Metadata;->titles:Ljava/util/List;

    invoke-interface {v0}, Ljava/util/List;->iterator()Ljava/util/Iterator;

    move-result-object v0

    :cond_1
    invoke-interface {v0}, Ljava/util/Iterator;->hasNext()Z

    move-result v2

    if-eqz v2, :cond_2

    invoke-interface {v0}, Ljava/util/Iterator;->next()Ljava/lang/Object;

    move-result-object v2

    check-cast v2, Ljava/lang/String;

    .line 134
    invoke-static {v2}, Lnl/siegmann/epublib/util/StringUtil;->isNotBlank(Ljava/lang/String;)Z

    move-result v3

    if-eqz v3, :cond_1

    return-object v2

    :cond_2
    :goto_0
    return-object v1
.end method

.method public getFormat()Ljava/lang/String;
    .locals 1

    .line 196
    iget-object v0, p0, Lnl/siegmann/epublib/domain/Metadata;->format:Ljava/lang/String;

    return-object v0
.end method

.method public getIdentifiers()Ljava/util/List;
    .locals 1
    .annotation system Ldalvik/annotation/Signature;
        value = {
            "()",
            "Ljava/util/List<",
            "Lnl/siegmann/epublib/domain/Identifier;",
            ">;"
        }
    .end annotation

    .line 190
    iget-object v0, p0, Lnl/siegmann/epublib/domain/Metadata;->identifiers:Ljava/util/List;

    return-object v0
.end method

.method public getLanguage()Ljava/lang/String;
    .locals 1

    .line 104
    iget-object v0, p0, Lnl/siegmann/epublib/domain/Metadata;->language:Ljava/lang/String;

    return-object v0
.end method

.method public getMetaAttribute(Ljava/lang/String;)Ljava/lang/String;
    .locals 1

    .line 212
    iget-object v0, p0, Lnl/siegmann/epublib/domain/Metadata;->metaAttributes:Ljava/util/Map;

    invoke-interface {v0, p1}, Ljava/util/Map;->get(Ljava/lang/Object;)Ljava/lang/Object;

    move-result-object p1

    check-cast p1, Ljava/lang/String;

    return-object p1
.end method

.method public getOtherProperties()Ljava/util/Map;
    .locals 1
    .annotation system Ldalvik/annotation/Signature;
        value = {
            "()",
            "Ljava/util/Map<",
            "Ljavax/xml/namespace/QName;",
            "Ljava/lang/String;",
            ">;"
        }
    .end annotation

    .line 61
    iget-object v0, p0, Lnl/siegmann/epublib/domain/Metadata;->otherProperties:Ljava/util/Map;

    return-object v0
.end method

.method public getPublishers()Ljava/util/List;
    .locals 1
    .annotation system Ldalvik/annotation/Signature;
        value = {
            "()",
            "Ljava/util/List<",
            "Ljava/lang/String;",
            ">;"
        }
    .end annotation

    .line 161
    iget-object v0, p0, Lnl/siegmann/epublib/domain/Metadata;->publishers:Ljava/util/List;

    return-object v0
.end method

.method public getRights()Ljava/util/List;
    .locals 1
    .annotation system Ldalvik/annotation/Signature;
        value = {
            "()",
            "Ljava/util/List<",
            "Ljava/lang/String;",
            ">;"
        }
    .end annotation

    .line 119
    iget-object v0, p0, Lnl/siegmann/epublib/domain/Metadata;->rights:Ljava/util/List;

    return-object v0
.end method

.method public getSubjects()Ljava/util/List;
    .locals 1
    .annotation system Ldalvik/annotation/Signature;
        value = {
            "()",
            "Ljava/util/List<",
            "Ljava/lang/String;",
            ">;"
        }
    .end annotation

    .line 110
    iget-object v0, p0, Lnl/siegmann/epublib/domain/Metadata;->subjects:Ljava/util/List;

    return-object v0
.end method

.method public getTitles()Ljava/util/List;
    .locals 1
    .annotation system Ldalvik/annotation/Signature;
        value = {
            "()",
            "Ljava/util/List<",
            "Ljava/lang/String;",
            ">;"
        }
    .end annotation

    .line 150
    iget-object v0, p0, Lnl/siegmann/epublib/domain/Metadata;->titles:Ljava/util/List;

    return-object v0
.end method

.method public getTypes()Ljava/util/List;
    .locals 1
    .annotation system Ldalvik/annotation/Signature;
        value = {
            "()",
            "Ljava/util/List<",
            "Ljava/lang/String;",
            ">;"
        }
    .end annotation

    .line 205
    iget-object v0, p0, Lnl/siegmann/epublib/domain/Metadata;->types:Ljava/util/List;

    return-object v0
.end method

.method public isAutoGeneratedId()Z
    .locals 1

    .line 52
    iget-boolean v0, p0, Lnl/siegmann/epublib/domain/Metadata;->autoGeneratedId:Z

    return v0
.end method

.method public setAuthors(Ljava/util/List;)V
    .locals 0
    .annotation system Ldalvik/annotation/Signature;
        value = {
            "(",
            "Ljava/util/List<",
            "Lnl/siegmann/epublib/domain/Author;",
            ">;)V"
        }
    .end annotation

    .line 88
    iput-object p1, p0, Lnl/siegmann/epublib/domain/Metadata;->authors:Ljava/util/List;

    return-void
.end method

.method public setContributors(Ljava/util/List;)V
    .locals 0
    .annotation system Ldalvik/annotation/Signature;
        value = {
            "(",
            "Ljava/util/List<",
            "Lnl/siegmann/epublib/domain/Author;",
            ">;)V"
        }
    .end annotation

    .line 100
    iput-object p1, p0, Lnl/siegmann/epublib/domain/Metadata;->contributors:Ljava/util/List;

    return-void
.end method

.method public setDates(Ljava/util/List;)V
    .locals 0
    .annotation system Ldalvik/annotation/Signature;
        value = {
            "(",
            "Ljava/util/List<",
            "Lnl/siegmann/epublib/domain/Date;",
            ">;)V"
        }
    .end annotation

    .line 76
    iput-object p1, p0, Lnl/siegmann/epublib/domain/Metadata;->dates:Ljava/util/List;

    return-void
.end method

.method public setDescriptions(Ljava/util/List;)V
    .locals 0
    .annotation system Ldalvik/annotation/Signature;
        value = {
            "(",
            "Ljava/util/List<",
            "Ljava/lang/String;",
            ">;)V"
        }
    .end annotation

    .line 169
    iput-object p1, p0, Lnl/siegmann/epublib/domain/Metadata;->descriptions:Ljava/util/List;

    return-void
.end method

.method public setFormat(Ljava/lang/String;)V
    .locals 0

    .line 193
    iput-object p1, p0, Lnl/siegmann/epublib/domain/Metadata;->format:Ljava/lang/String;

    return-void
.end method

.method public setIdentifiers(Ljava/util/List;)V
    .locals 0
    .annotation system Ldalvik/annotation/Signature;
        value = {
            "(",
            "Ljava/util/List<",
            "Lnl/siegmann/epublib/domain/Identifier;",
            ">;)V"
        }
    .end annotation

    .line 185
    iput-object p1, p0, Lnl/siegmann/epublib/domain/Metadata;->identifiers:Ljava/util/List;

    const/4 p1, 0x0

    .line 186
    iput-boolean p1, p0, Lnl/siegmann/epublib/domain/Metadata;->autoGeneratedId:Z

    return-void
.end method

.method public setLanguage(Ljava/lang/String;)V
    .locals 0

    .line 107
    iput-object p1, p0, Lnl/siegmann/epublib/domain/Metadata;->language:Ljava/lang/String;

    return-void
.end method

.method public setMetaAttributes(Ljava/util/Map;)V
    .locals 0
    .annotation system Ldalvik/annotation/Signature;
        value = {
            "(",
            "Ljava/util/Map<",
            "Ljava/lang/String;",
            "Ljava/lang/String;",
            ">;)V"
        }
    .end annotation

    .line 216
    iput-object p1, p0, Lnl/siegmann/epublib/domain/Metadata;->metaAttributes:Ljava/util/Map;

    return-void
.end method

.method public setOtherProperties(Ljava/util/Map;)V
    .locals 0
    .annotation system Ldalvik/annotation/Signature;
        value = {
            "(",
            "Ljava/util/Map<",
            "Ljavax/xml/namespace/QName;",
            "Ljava/lang/String;",
            ">;)V"
        }
    .end annotation

    .line 64
    iput-object p1, p0, Lnl/siegmann/epublib/domain/Metadata;->otherProperties:Ljava/util/Map;

    return-void
.end method

.method public setPublishers(Ljava/util/List;)V
    .locals 0
    .annotation system Ldalvik/annotation/Signature;
        value = {
            "(",
            "Ljava/util/List<",
            "Ljava/lang/String;",
            ">;)V"
        }
    .end annotation

    .line 158
    iput-object p1, p0, Lnl/siegmann/epublib/domain/Metadata;->publishers:Ljava/util/List;

    return-void
.end method

.method public setRights(Ljava/util/List;)V
    .locals 0
    .annotation system Ldalvik/annotation/Signature;
        value = {
            "(",
            "Ljava/util/List<",
            "Ljava/lang/String;",
            ">;)V"
        }
    .end annotation

    .line 116
    iput-object p1, p0, Lnl/siegmann/epublib/domain/Metadata;->rights:Ljava/util/List;

    return-void
.end method

.method public setSubjects(Ljava/util/List;)V
    .locals 0
    .annotation system Ldalvik/annotation/Signature;
        value = {
            "(",
            "Ljava/util/List<",
            "Ljava/lang/String;",
            ">;)V"
        }
    .end annotation

    .line 113
    iput-object p1, p0, Lnl/siegmann/epublib/domain/Metadata;->subjects:Ljava/util/List;

    return-void
.end method

.method public setTitles(Ljava/util/List;)V
    .locals 0
    .annotation system Ldalvik/annotation/Signature;
        value = {
            "(",
            "Ljava/util/List<",
            "Ljava/lang/String;",
            ">;)V"
        }
    .end annotation

    .line 147
    iput-object p1, p0, Lnl/siegmann/epublib/domain/Metadata;->titles:Ljava/util/List;

    return-void
.end method

.method public setTypes(Ljava/util/List;)V
    .locals 0
    .annotation system Ldalvik/annotation/Signature;
        value = {
            "(",
            "Ljava/util/List<",
            "Ljava/lang/String;",
            ">;)V"
        }
    .end annotation

    .line 208
    iput-object p1, p0, Lnl/siegmann/epublib/domain/Metadata;->types:Ljava/util/List;

    return-void
.end method
